database:
  daitss_connection_string: postgres://daitss:topsecret@localhost/daitss_db
  storemaster_connection_string: postgres://storemaster:topsecret@localhost/daitss_db
  silo_connection_string: postgres://silo:topsecret@localhost/store_db

silos:
  temp_dir_env: /var/daitss/
  silo_connection_string: postgres://silo:mysecret@localhost/test_store_db

store-master.fcla.edu:
  required_pools: 2

daitss:

fixity:
  expiration_days: 45
  stale_days: 60

funky-section:
  funky-key:  funky value
